### ISSUE TITLE
Feature request: Create a discord, a vscode or intelij plugin and a language proposal for this.

### ISSUE THREAD

**Issue by Whizboy-Arnold** [sbosley/java-traits#5]
Hey I absolutely love the idea and implementation behind this, its been a long time i have searching for such. Could you also create a community on discord or here to be able to discuss, suggest, contribute and follow up better on progress. I would like an official proposal to java to create such a feature. I absolutely love Traits especially how handy they are in Laravel PHP, and how it is great to refactor large classes,  I don't understand how such is not in official java or kt spec. I think it may be time for a better jvm language with modern features such as await, deconstruction and traits such as in languages like Typescript and php, all while within strict typing of java.

**Comment by Whizboy-Arnold** [comment]
there is this article [Traits with Default methods](https://opencredo.com/blogs/traits-java-8-default-methods/ ) that tries to address the issue long time, however it fails to address the fact that in traits in languages like php, you can access and declare member variables which is not the case in java. Unless you declare getters on the interface, which can be tedious and undesirable. Also fails to address the fact that the methods now have to be public.  This is the first implementation that i think is close enough hope it is a success in getting the actual great feel of Traits.

**Comment by sbosley** [comment]
Hey, thanks for reaching out! I'm glad you find the project interesting and useful, but I'm afraid it's pretty much been abandoned. The original intended use case was for something like default methods on Android, which was stuck on Java 1.6 without them for a long while, but Android has long since moved to more modern Java and/or Kotlin, so I'm not using or maintaining this project anymore.

If you'd like to experiment with it anyways, you should feel free to fork and/or modify under the terms of the license. If you're interested in JVM languages with large feature sets, I also recommend checking out [Scala](https://www.scala-lang.org), which is my personal preferred JVM language and does have a nice implementation of traits (among many many other useful features).
